with open('extra_alleles.txt', 'r') as f:
    alleles = f.read()
alleles = alleles.split('\n')
alleles = [a.strip() for a in alleles]

query = (
"""-- This query is autogenerated by print_extra_allele_query.py, do not edit here.
COPY (SELECT DISTINCT 
'FlyBase:'||a.uniquename AS allele_id,
string_agg(DISTINCT a.name, '|') AS allele_name, 
string_agg(DISTINCT s.name, '|') AS allele_synonyms
FROM feature a
LEFT JOIN feature_synonym fs ON a.feature_id=fs.feature_id AND a.is_obsolete='f'
LEFT JOIN synonym s ON fs.synonym_id=s.synonym_id
WHERE a.uniquename IN ('%s')
GROUP BY allele_id
) TO STDOUT WITH DELIMITER E'\\t' CSV HEADER;
""" % "', '".join(alleles))

with open('../sql/extra_allele_query.sql', 'w') as f:
    f.write(query)