SELECT DISTINCT ?term
WHERE {
  { ?s1 ?p1 ?term . }
  UNION
  { ?term ?p2 ?o2 . }
  FILTER(isIRI(?term) && (regex(str(?term), UCASE("VFB_drivers_")) || regex(str(?term), "http://virtualflybrain.org/reports/VFBexp_")))
}
