name: auto_release

on:

  schedule:
  - cron: "30 11 * * *"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull
    
    steps:
    - uses: actions/checkout@v2

    - name: Run ontology release
      env:
        DEFAULT_BRANCH: master
      run: cd src/ontology && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' update_ontology -B && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' prepare_release -B

