name: auto_release

on:

  schedule:
  - cron: "0 0 * * 1"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull
    
    steps:
    - uses: actions/checkout@v3

    - name: Run ontology release
      env:
        DEFAULT_BRANCH: master
      run: cd src/ontology && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' update_ontology -B && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' prepare_release -B

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Automated release'
        add: '["*.owl", "*.obo", "*.json", "src/ontology/imports/*.owl", "src/ontology/VFB_drivers-edit.owl"]'
